FORMAT: 1A
HOST: https://collab-a-block.org/

# Collab-a-Block

Collab-a-Block is a simple API allowing neighbours to lookup each other to collaborate on local matters.

## Login Page [/]

## Lookup Houses [/houses]

### List All Houses [GET]

+ Response 200 (application/json)

[
    {
        "id": 1,
        "address": [{
                    "postcode" : "AB1 2CD",
                    "street" : "Orchard Street"
                    }],
        "owner": [{
                    "name" : "Samekah Howard",
                    "age" : 23,
                    "residentNumber": 2
                }]
   }, 
           "id": 2,
        "address": [{
                    "postcode" : "AB1 2CD",
                    "street" : "Orchard Street"
                    }],
        "owner": [{
                    "name" : "Rafika Ruremis",
                    "age" : 24,
                    "residentNumber": 3
                }]
]

## Lookup Houses [/houses/:address]
### Lookup a Particular House [GET]

+ Response 200 (application/json)

[
   {
     "id": 1,
     "address": [{
                  "postcode" : "AB1 2CD",
                  "street" : "Orchard Street"
                }],
     "owner": [{
                  "name" : "Samekah Howard",
                  "age" : 23,
                  "residentNumber": 2
                }]
   }
]


## Lookup Residents by Name[/owner/:name]
### Lookup a Resident by Name [GET]

+ Response 200 (application/json)

{
    "name" : "Samekah Howard",
    "age" : 23,
    "residentNumber": 2
}


## Lookup Residents by Age Bracket[/owner?minAge=18]
### Lookup a Resident by Age Bracket [GET]

+ Response 200 (application/json)

{
    "name" : "Samekah Howard",
    "age" : 23,
    "residentNumber": 2
}


## Lookup Residents by Household Size[/owner/size?minSize=2]
### Lookup a Resident by Household Size[GET]

+ Response 200 (application/json)

{
    "name" : "Samekah Howard",
    "age" : 23,
    "residentNumber": 2
}