FORMAT: 1A
HOST: https://collab-a-block.org/

# Collab-a-Block

Collab-a-Block is a simple API allowing neighbours to lookup each other and collaborate on local matters.

## Login Page [/]

### Lookup Houses [/houses]

#### List All Houses [GET]

+ Response 200 (application/json)

        [
                    {
                        "full address": "1 Orchard Street, London SW1 3RZ",
                        "owner": "Samekah Howard" 
                    }, {
                        "full address": "2 Orchard Street, London SW1 3RZ",
                        "owner": "Rafika Turemis" 
                    }, {
                        "full address": "3 Orchard Street, London SW1 3RZ",
                        "owner": "Polina Moore" 
                    }, {
                        "full address": "4 Orchard Street, London SW1 3RZ",
                        "owner": "Freddie Moore" 
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may add a household to the collaborative neighbourhood by using this action. It takes a JSON
object containing a ____

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }